management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

server:
  port: 12349
  connection-timeout: 30000

      
spring:
  application:
    name: lakehouse
    
  datasource:
    hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    tomcat:
      initial-size: 50
      max-wait: 80000
      max-active: 600
      max-idle: 100
      min-idle: 30
      removeAbandoned: true
      removeAbandonedTimeout: 800
      timeBetweenEvictionRunsMillis: 3400000
      minEvictableIdleTimeMillis: 5500000
      default-auto-commit: false  
    url: '${POSTGRES_ASSET_URI:jdbc:postgresql://lakehousedb:5432/lakehousedb}'
    username: '${PGASSET_USER:postgres}'
    password: '${PGASSET_PASSWORD:cp8@2a#ol}'
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: 'SELECT 1'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  kafka:   
    listener:
      ack-mode: MANUAL
    producer:
      batch-size: 1048570000
      bootstrap-servers: kafka1:9092,kafka2:9093
      buffer-memory: 97938193
      client-id: lakehouse
      group-id: lakehouse
      retries: 10      
    consumer:
      bootstrap-servers: kafka1:9092,kafka2:9093
      group-id: lakehouse
      auto-offset-reset: earliest         
      enable-auto-commit: false
      session.timeout.ms: 30000
      max-poll-records: 10
      fetch-max-wait: 100
      fetch-min-size: 504857600
